INSERT INTO COZINHAS(ID, NOME) VALUES (1,'Brasileira');
INSERT INTO COZINHAS(ID, NOME) VALUES (2,'Tailandesa');
INSERT INTO COZINHAS(ID, NOME) VALUES (3,'Indiana');

INSERT INTO RESTAURANTES(ID, TAXA_FRETE, NOME, cozinha_nome) VALUES (1,10.70,'Papila Deli', 'Tailandesa');
INSERT INTO RESTAURANTES(ID, TAXA_FRETE, NOME, cozinha_nome) VALUES (2,19.99,'O Gaiteiro', 'Brasileira');
INSERT INTO RESTAURANTES(ID, TAXA_FRETE, NOME, cozinha_nome) VALUES (3,15.45,'Tutto in Famiglia','Indiana');
